[CmdletBinding()]
param([string]$Version,[string]$OutputDirectory='', [string]$SigningCertificate,[switch]$SkipTests,[switch]$Unsigned)
$ErrorActionPreference='Stop'
$repo=Split-Path -Parent $PSScriptRoot
. (Join-Path $PSScriptRoot 'build-common.ps1')
$artifacts=Join-Path $repo 'artifacts'; $staging=Join-Path $artifacts 'installer-staging'; $publish=Join-Path $artifacts 'commercial\Release'
if ([string]::IsNullOrWhiteSpace($OutputDirectory)) {
  $outName=([char]0x0041)+([char]0x0049)+([char]0x6267)+([char]0x884c)+([char]0x8f6f)+([char]0x4ef6)+([char]0x5b89)+([char]0x88c5)+([char]0x5305)
  $OutputDirectory=Join-Path (Split-Path (Split-Path $repo -Parent) -Parent) $outName
}
$installerOutput=[IO.Path]::GetFullPath($OutputDirectory); $iss=Join-Path $repo 'installer\VisionWorkbench.iss'; $innoBuildDir=Join-Path (Split-Path $repo -Parent) 'InnoSetup'; if(Test-Path $innoBuildDir){$env:PATH="$innoBuildDir;$env:PATH"}
function Invoke-Native { param([string]$FilePath,[string[]]$Arguments); & $FilePath @Arguments; if ($LASTEXITCODE -ne 0) { throw "Command failed: $FilePath ($LASTEXITCODE)" } }
function Copy-TreeFiltered { param([string]$Source,[string]$Destination)
  New-Item -ItemType Directory -Force -Path $Destination | Out-Null
  $excluded=@('.venv','.pytest_cache','__pycache__','.pip-download','test','tests','datasets','runs','temp')
  Get-ChildItem -LiteralPath $Source -Recurse -File | Where-Object {
    $relative=$_.FullName.Substring($Source.Length).TrimStart('\'); $parts=$relative.Split('\')
    ($parts | Where-Object {$excluded -contains $_}).Count -eq 0 -and $_.Extension -notin @('.pyc','.pyo','.log','.pt','.pth','.onnx','.engine')
  } | ForEach-Object { $relative=$_.FullName.Substring($Source.Length).TrimStart('\'); $target=Join-Path $Destination $relative; New-Item -ItemType Directory -Force -Path (Split-Path -Parent $target) | Out-Null; Copy-Item -LiteralPath $_.FullName -Destination $target -Force }
}
function Get-ProjectVersion { if (-not [string]::IsNullOrWhiteSpace($Version)) {return $Version.Trim()}; $p=Get-Content (Join-Path $repo 'Directory.Build.props') -Raw; $m=[regex]::Match($p,'\x3cVersion>([^\x3c]+)'); if(-not $m.Success){throw 'Project version is missing.'}; return $m.Groups[1].Value.Trim() }
function Resolve-Dotnet { return Resolve-ProjectDotnet $repo }
function Resolve-PythonBase { $py=Get-Command py -ErrorAction SilentlyContinue; if($null -eq $py){throw 'Python 3.12 x64 is required.'}; $p=(& $py.Source -3.12 -c 'import sys; print(sys.base_prefix)')|Select-Object -Last 1; if($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($p) -or -not(Test-Path(Join-Path $p 'python.exe'))){throw 'Python 3.12 x64 base runtime was not found.'}; return $p.Trim() }
function Build-PythonRuntime { param([string]$Destination); $venv=Join-Path $repo 'workers\yolo11\.venv'; if(-not(Test-Path(Join-Path $venv 'Lib\site-packages\torch'))){throw "Locked YOLO11 runtime missing: $venv"}; Copy-TreeFiltered (Resolve-PythonBase) $Destination; $site=Join-Path $Destination 'Lib\site-packages'; New-Item -ItemType Directory -Force -Path $site|Out-Null; Copy-TreeFiltered (Join-Path $venv 'Lib\site-packages') $site; Remove-Item -LiteralPath (Join-Path $Destination 'Scripts') -Recurse -Force -ErrorAction SilentlyContinue; Remove-Item -LiteralPath (Join-Path $site 'onnx\backend\test') -Recurse -Force -ErrorAction SilentlyContinue; foreach($optional in @('tensorrt_libs','tensorrt','~orch','_polars_runtime_32','playwright','onnx','onnxruntime_gpu','pythonwin','wxautox','seaborn','matplotlib','sympy','pandas')){Remove-Item -LiteralPath (Join-Path $site $optional) -Recurse -Force -ErrorAction SilentlyContinue}; $python=Join-Path $Destination 'python.exe'; if(-not(Test-Path $python)){throw 'Python runtime assembly failed.'}; $probe=& $python -c 'import sys,torch,cv2,ultralytics; print(sys.version.split()[0]); print(torch.__version__); print(cv2.__version__); print(ultralytics.__version__)'; if($LASTEXITCODE -ne 0){throw 'Bundled Python import probe failed.'}; Set-Content (Join-Path $Destination 'runtime-lock.txt') ($probe -join [Environment]::NewLine) -Encoding UTF8 }
function Resolve-MvsRuntime { $candidates=@('C:\Program Files\Common Files\MVS\Runtime\Win64_x64','C:\Program Files (x86)\Common Files\MVS\Runtime\Win64_x64'); foreach($candidate in $candidates){if(Test-Path (Join-Path $candidate 'MvCameraControl.dll')){return $candidate}}; throw 'Authorized x64 MVS Runtime was not found.' }
function Build-MvsRuntime { param([string]$Destination); $source=Resolve-MvsRuntime; if(Test-Path $Destination){Remove-Item $Destination -Recurse -Force}; Copy-TreeFiltered $source $Destination; if(-not(Test-Path (Join-Path $Destination 'MvCameraControl.dll'))){throw 'MVS Runtime assembly failed.'}; $records=Get-FileRecords $Destination; $records|ConvertTo-Json -Depth 5|Set-Content (Join-Path $Destination 'mvs-runtime-manifest.json') -Encoding UTF8 }
function Get-FileRecords { param([string]$Root); @(Get-ChildItem -LiteralPath $Root -Recurse -File|ForEach-Object{[ordered]@{path=$_.FullName.Substring($Root.Length+1).Replace('\','/');size=$_.Length;sha256=(Get-FileHash $_.FullName -Algorithm SHA256).Hash.ToLowerInvariant()}}) }
$v=Get-ProjectVersion; if($v -notmatch '^\d+(\.\d+){1,3}$'){throw "Invalid installer version: $v"}; New-Item -ItemType Directory -Force -Path $installerOutput|Out-Null; $reuseRuntime=Test-Path (Join-Path $staging 'runtime\python\runtime-lock.txt'); if($reuseRuntime){Clear-ProjectBuildOutput $repo $staging @('runtime')}else{Clear-ProjectBuildOutput $repo $staging}; New-Item -ItemType Directory -Force -Path $staging|Out-Null
if((& git -C $repo status --short)){Write-Warning 'Working tree has changes; publishing current tree.'}; $dotnet=Resolve-Dotnet
Invoke-Native $dotnet @('restore',(Join-Path $repo 'VisionWorkbench.slnx'),'-r','win-x64'); Invoke-Native $dotnet @('build',(Join-Path $repo 'src\VisionWorkbench.App\VisionWorkbench.App.csproj'),'-c','Release','--no-restore'); if(-not $SkipTests){Invoke-Native $dotnet @('test',(Join-Path $repo 'tests\VisionWorkbench.Tests\VisionWorkbench.Tests.csproj'),'-c','Release','--no-restore','--filter','FullyQualifiedName!~UiSmokeTests')}; Clear-ProjectBuildOutput $repo $publish; Invoke-Native $dotnet @('publish',(Join-Path $repo 'src\VisionWorkbench.App\VisionWorkbench.App.csproj'),'-c','Release','-r','win-x64','--self-contained','true','--no-restore','-o',$publish)
Get-ChildItem -LiteralPath $publish -Force|Copy-Item -Destination $staging -Recurse -Force; if(-not $reuseRuntime){Build-PythonRuntime (Join-Path $staging 'runtime\python')}; Build-MvsRuntime (Join-Path $staging 'runtime\mvs\Win64_x64')
$plugins=Join-Path $staging 'plugins'; if(Test-Path $plugins){Remove-Item $plugins -Recurse -Force}; foreach($name in @('atu5','yolo11','yoloe','sam1','paddleocr-vl','sample-counter','sample-flow-counter','python-sdk')){$src=Join-Path $repo "workers\$name";if(Test-Path $src){Copy-TreeFiltered $src (Join-Path $plugins $name)}}
$modelPath=Join-Path $repo 'installer\model-manifest.json'; Copy-Item $modelPath (Join-Path $staging 'model-manifest.json') -Force; $models=Get-Content $modelPath -Raw|ConvertFrom-Json; foreach($m in @($models.models|Where-Object{$_.included -eq $true})){$src=Join-Path $repo $m.source;$dst=Join-Path $staging $m.target;if(-not(Test-Path $src)){throw "Model missing: $src"};New-Item -ItemType Directory -Force -Path (Split-Path -Parent $dst)|Out-Null;Copy-Item $src $dst -Force;if((Get-FileHash $dst -Algorithm SHA256).Hash.ToLowerInvariant() -ne $m.sha256.ToLowerInvariant()){throw "Model hash mismatch: $($m.name)"}}
$lock=Get-Content(Join-Path $staging 'runtime\python\runtime-lock.txt') -ErrorAction SilentlyContinue; $manifest=[ordered]@{product='VisionWorkbench';version=$v;buildTimeUtc=[DateTime]::UtcNow.ToString('o');gitCommit=(& git -C $repo rev-parse HEAD).Trim();architecture='win-x64';pythonRuntime=($lock -join '; ');workers=(Get-FileRecords $plugins);models=$models.models;codeSigned=$false;unsignedReason='No code-signing certificate was provided.'}; $manifest|ConvertTo-Json -Depth 8|Set-Content(Join-Path $staging 'release-manifest.json') -Encoding UTF8
$notesName=([char]0x5B89)+([char]0x88C5)+([char]0x8BF4)+([char]0x660E)+'.txt';$notesPath=Join-Path $staging $notesName;Set-Content $notesPath @('VisionWorkbench Installation Notes','Bundled .NET and fixed Python runtime.','Customer data is preserved in C:\ProgramData\VisionWorkbench.','NVIDIA GPU is automatic with CPU fallback.','Authorized x64 Hikvision MVS Runtime is bundled under runtime\mvs\Win64_x64.','This build is unsigned until a release certificate is supplied.') -Encoding UTF8
$iscc=Get-Command ISCC.exe -ErrorAction SilentlyContinue;if($null -eq $iscc){$isccPath=@('E:\AI执行软件\InnoSetup\ISCC.exe','C:\Program Files (x86)\Inno Setup 6\ISCC.exe','C:\Program Files\Inno Setup 6\ISCC.exe')|Where-Object{Test-Path $_}|Select-Object -First 1}else{$isccPath=$iscc.Source};if(-not$isccPath){throw 'Inno Setup 6 ISCC.exe was not found.'};Invoke-Native $isccPath @('/Qp',"/DMyAppVersion=$v","/O$installerOutput",$iss)
$setup=Join-Path $installerOutput 'VisionWorkbench-Setup-x64.exe';if(-not(Test-Path $setup)){throw "Installer was not generated: $setup"};$hash=(Get-FileHash $setup -Algorithm SHA256).Hash.ToLowerInvariant();Set-Content "$setup.sha256" "$hash  VisionWorkbench-Setup-x64.exe" -Encoding ASCII;$manifest.installPackage=[ordered]@{path='VisionWorkbench-Setup-x64.exe';size=(Get-Item $setup).Length;sha256=$hash};$manifest|ConvertTo-Json -Depth 8|Set-Content(Join-Path $installerOutput 'release-manifest.json') -Encoding UTF8;Copy-Item $notesPath (Join-Path $installerOutput $notesName) -Force;Write-Host "Installer: $setup";Write-Host "SHA-256: $hash";Write-Host 'Signed: False'
